### ISSUE TITLE
axol.io faucet

### ISSUE THREAD

**Issue by Hydepwns** [eth-clients/holesky#101]
hey there ETH pandaops cc @q9f @pk910 --

Axol.io is our new LATAM nodeops company and we would like to support the Holesky testnet by running a **Non-KYC faucet**. Could we possibly have ~32k ETH to spin up validators?

We are a team of 3 engineers, previously ran a lot of blockdaemons infra!

Holesky account we plan to use to fund the validators:
`0x9E051C7a42489CF5dfbbFD2Ee7012b69FcAa200E` 

Happy to answer any questions or jump on a call if necessary sers!

**Comment by pk910** [comment]
Heya @Hydepwns,
I don't get it,  do you want to run a faucet or spin up validators?
If you want to run a faucet, where is it and how does your protection mechanism work?

**Comment by Hydepwns** [comment]
apologies for ambiguity--
- we would like to support testnet by running validators, and using all holETH collected to help refill the faucet.
- we would fork your POW faucet and have it on our website axol.io (we are launching this friday).

**Comment by pk910** [comment]
Heya @Hydepwns,
I've done some sanity check, and it looks good :)
But, trying to use rewards from setting up validators to keep your faucet filled won't really work. 
The amount you get from 1,000 validators isn't enough for a faucet when there are more than 1.5 million validators in the network.

We still want to help you out. We can give you a initial 10,000 HolETH per month to keep your faucet funded.
We'll see how things go and can talk about changing this later based on how much your faucet is used.

I've sent you a starting amount of 5,000 HolETH. Please go ahead and set up your faucet on your site and launch it. Once your site is up, we'll set up the proper ongoing funding mechanism.

Looking forward to your site going live and we can adjust the support as needed in the future.

**Comment by Hydepwns** [comment]
roger that, you're correct. We just wanted to ask for a reasonable amount at first and slowly scale into a larger operation after proving our reliability.

We will be in touch once the faucet is live and we have the validators up and running (within two weeks). Thank you so much.
