### ISSUE TITLE
Requesting Holesky ETH for gas relay

### ISSUE THREAD

**Issue by kartojal** [eth-clients/holesky#105]
Hi!

Building a new gas relay for gas-less deployments in [Catapulta](https://catapulta.sh/), and would need 1000 ETH to allow devs to try it out.

Could you send 1000 ETH to this address ?

0xeF987CdE72bC6A9e351d2460214d75f095b1b862

Thanks a lot.

(i also requested in Sepolia testnet!)

**Comment by willwinning** [comment]
come here to buy 

http://www.gaswap.top:8061/

**Comment by parithosh** [comment]
Please make the request in this repository instead: https://github.com/ethpandaops/fundingvault/
