### ISSUE TITLE
Commit to run a genesis validator - (A) Client Teams

### ISSUE THREAD

**Issue by q9f** [eth-clients/holesky#11]
The Ethereum EL/CL client teams are asked to commit to a number of validators they are willing to run at genesis for Holesky.

The recommended size of the validator-set per team is 80-100k. The estimated lifetime should be 3-5 years.

Please also indicate if you believe that a genesis with 1.5 million keys could cause issues.

**Comment by parithosh** [comment]
EF DevOps commits to running 100k validators, We're also comfortable to run more or less depending on the network's needs.

**Comment by antondlr** [comment]
Sigma Prime will happily commit to 100k validators (or any other size that is deemed ideal for client teams)

**Comment by tersec** [comment]
Status/Nimbus commits to running 100k validators, or however many is useful for the network.

**Comment by lucassaldanha** [comment]
ConsenSys commits to run 100k validators or more if needed.

**Comment by philknows** [comment]
ChainSafe/Lodestar committing to 100k validators.

**Comment by MarekM25** [comment]
Nethermind commits to running 100k validators

**Comment by sauliusgrigaitis** [comment]
Grandine would take 50K-100K validators.

**Comment by MarekM25** [comment]
Nethermind commits to run 100k validators ;)

**Comment by nisdas** [comment]
The Prysm team would be fine with running a 100k validators or a higher number if required.

**Comment by parithosh** [comment]
Thank you for your participation. The comments have been noted and will make it into the genesis state. We'll be in touch for information about genesis state, etc. For more info please refer to the community call #1 notes: https://github.com/ethereum/pm/issues/814#issuecomment-1613224057
