### ISSUE TITLE
Commit to run a genesis validator - (B) Node Operators/L2s

### ISSUE THREAD

**Issue by q9f** [eth-clients/holesky#12]
The Ethereum node operateors and layer-2s are invited to commit to a number of validators they are willing to run at genesis for Holesky.

There is no recommended size here, but it would be suggested to commit to at least 10k keys. The estimated lifetime should be 3-5 years.

**Comment by mcdee** [comment]
Attestant are happy to run a maximum of 100K validators from genesis.

**Comment by nalepae** [comment]
Kiln is happy to run 100K validators as well.

**Comment by franono** [comment]
Simply Staking commits to running 100k validators

**Comment by sambacha** [comment]
> The Ethereum node operateors and layer-2s are invited to commit to a number of validators they are willing to run at genesis for Holesky.
> 
> 
> 
> There is no recommended size here, but it would be suggested to commit to at least 10k keys. The estimated lifetime should be 3-5 years.

Based off of the call last week, a majority of validators should be of type-0 withdrawal credentials.

We are wanting to explore DVT usage as well, are their any restrictions as to validator operations from genesis state to when the chain is declared viable and "stable" to which we can loosen up restrictions on these sorts of things? 

Thanks

**Comment by g11tech** [comment]
blockblaz (g11tech initiative) is happy to run 10k keys

**Comment by LukeHackett12** [comment]
Obol Labs is happy to run 10k validators from genesis

**Comment by rocknet** [comment]
A coordinated set of Rocket Pool node operators commits to running 100k validators from genesis.

**Comment by uink45** [comment]
Pier Two would be happy to run up to 100,000 validators for the lifetime of the testnet.

**Comment by Gandalf-Dust-Wizard** [comment]
RockX would be happy to run up to 50,000 validators for the lifetime of the testnet.

**Comment by PacoBits** [comment]
Stakely is happy to run up to 50k validators from genesis.

**Comment by gabriellassh** [comment]
Chorus One can commit to the min of 10k validators at genesis, final number pending.

**Comment by eth2353** [comment]
Serenita can commit to run up to 20k validators.

**Comment by philknows** [comment]
> Based off of the call last week, a majority of validators should be of type-0 withdrawal credentials.

> We are wanting to explore DVT usage as well, are their any restrictions as to validator operations from genesis state to when the chain is declared viable and "stable" to which we can loosen up restrictions on these sorts of things?

> Thanks

We can discuss on this on the call today, but I'm of the opinion that at least for genesis we should have a large supermajority, if not all, of the network commitments being made here to just be reliable, stable node operators for network stability. There will be ample opportunity similar to Goerli for experimenters to join the network after it's up and running.

**Comment by parithosh** [comment]
Thank you for your participation. The comments have been noted and will make it into the genesis state. We'll be in touch for information about genesis state, etc. For more info please refer to the community call #1 notes: https://github.com/ethereum/pm/issues/814#issuecomment-1613224057

**Comment by Tomas-Eminger** [comment]
RockawayX Infra can commit up to 100k validators from Genesis to the end.

**Comment by daizhengxue** [comment]
Chainbase Labs is happy to run 10k validators from genesis.

**Comment by 0xalex88** [comment]
@q9f seems not everyone made into the list on #24, is there any specific reason?

**Comment by samkazemian** [comment]
Hey @q9f is there a reason you guys excluded Frax Finance? We're literally the top all time performant validator set according to rated.network effectiveness rankings on mainnet. And we're the #4 largest LSD with frxETH. @0xalex88 from our team requested with everyone else when the issue was open. Can we please be included in this batch?

**Comment by q9f** [comment]
No specific reasons. We ran tests and had issues to run networks with a genesis of more than 1.6 million validators.

Your options are now either or
- submit a PR with your public keys : withdrawal prefix (see open PRs) and we consider it if not enough teams submit by end of week
- ask for a genesis allocation to make a deposit right after launch to join the validator set

Nobody will be excluded but there are some certain constraints for the actual genesis.

**Comment by samkazemian** [comment]
Thanks for the quick reply @q9f appreciate it sir! @0xalex88 will ask for a genesis alloc as part of the Frax core devs. Everything sounds good :)

**Comment by 0xNODE3** [comment]
Hello there!

We sincerely apologize for the delay in submitting our application. [Node3](https://www.node3.tech/) is fully dedicated to decentralization, planning to operating 50,000 validators with a focus on both EL and CL minorities. Our infrastructure, located in Australia, is exclusively on-premises and dedicated to Holesky over lifetime.

If it remains feasible, we kindly request you to reach out to me through Telegram at @peterlin0509 or via email at [peter.lin@node3.tech](mailto:peter.lin@node3.tech). Thank you for your understanding.

Much appreciated!
