### ISSUE TITLE
Commit to run a genesis validator - (C) Others

### ISSUE THREAD

**Issue by q9f** [eth-clients/holesky#13]
The Ethereum stakers and other enthusiasts are invited to commit to a number of validators they are willing to run at genesis for Holesky.

There is no recommended size here, but it would be suggested to commit to at least 10k keys. The estimated lifetime should be 3-5 years.

**Comment by sambacha** [comment]
> The Ethereum stakers and other enthusiasts are invited to commit to a number of validators they are willing to run at genesis for Holesky.
> 
> 
> 
> There is no recommended size here, but it would be suggested to commit to at least 10k keys. The estimated lifetime should be 3-5 years.

Manifold Finance, 36_000 validators running:
10_000 * 3 clients
6_000 * running various versions of the main 3 operating clients to test bleeding edge and latest release versions of said clients.

sam@manifoldfinance.com
@sambacha on tg

**Comment by zhongfu** [comment]
willing to commit to 10_000 validators

@zhongfu on tg

**Comment by Gaurangas** [comment]
Would love to run 10k validators

**Comment by stakelocal** [comment]
I will commit to running 10,000 Holesky validators.

**Comment by metanull-operator** [comment]
Throwing my hat into the “other” group here, because I assume there must be a reason “node operators” are a separate class. I can commit to 10,000 validators either way.

**Comment by remyroy** [comment]
EthStaker is committing to run 40,000 genesis validators on Holesky for 3-5 years.

**Comment by fredriksvantes** [comment]
Commiting to run 100,000 validators on Hoelsky for its lifetime on 5-7 dedicated hosts, depending on load, in a Swedish datacenter. These will be running on a variety of clients, with mev enabled, and be connected to a potentially public elasticsearch cluster to provide monitoring, analytics, anomaly detection and assistance during potential incidents. It is also planned for these validators to produce documentation for running enterprise grade staking platforms.

**Comment by uink45** [comment]
Pier Two would be happy to run up to 100,000 validators for the lifetime of the testnet.

**Comment by mattstam** [comment]
Committing to run 10k validators on Holesky for its lifetime. History of running mainnet validators as an independent operator.

tg: @mattstam, discord mattstam#3434

**Comment by ralexstokes** [comment]
I'd be happy to run 5000 validators at genesis, tg: ralexstokes

**Comment by protolambda** [comment]
Interested to run 10,000 validators. tg: protolambda

**Comment by infosecual** [comment]
Happy to run 10,000 validators. tg: infosecual

**Comment by sambacha** [comment]
@parithosh / @q9f would it be possible to setup a telegram group for purposes of facilitating coordination/plan ing etc? I prefer not to use discord and most people in this thread have responded with their TG username. 

Also if there is work on a web site can certainly help with that as well!

**Comment by arnetheduck** [comment]
@arnetheduck / 10k

**Comment by jgorfenger** [comment]
I'd like to run 10,000 validators at genesis. I'd consider myself an ETH enthusiast.

**Comment by easeev** [comment]
We at @chainstack are willing to run 10K validators

@easeev on Telegram/Discord

**Comment by theSamPadilla** [comment]
Hey all!

I know this issue is closed but in case we could do a final opening, [Google Cloud Web3](http://googl3cloud.com/) would love to run **10k validators for the entirety of Holesky's lifetime.**

We have been supporting the ETH ecosystem for a while now, having recently launched our Eth Node service product - [Blockhain Node Engine](https://cloud.google.com/blockchain-node-engine) and planning to do more stuff too.

@theSamPadilla on Twitter/Telegram

**Comment by stefa2k** [comment]
Apologies, a bit late to the party.

[RockLogic](https://www.rocklogic.at/) would love to run **50k validators for the entire Holesky lifetime** distributed over all supported execution (5) & consensus clients (5) supported by [Stereum](https://github.com/stereum-dev/ethereum-node).

How to find us:
- Me: https://twitter.com/Stefa2kEth & TG: stefa2k & Discord: stefa2k.eth
- Stereum: https://stereum.net/ & https://github.com/stereum-dev/ethereum-node & https://twitter.com/stereumdev & https://discord.gg/Wnt7KFjKe7

**Comment by SimonSMH1015** [comment]
Hello, 
[Huawei Cloud Blocklchain Lab ](https://www.huaweicloud.com/intl/en-us/product/bcs/nes.html) is willing to run 10k validators for the Holesky testnet. We noticed that the new testnet is comming and the Genesis block is full. But still we are happy to maintains those validatores once the testnet launched. 

Contact us by:
Web3 Node engine Service: https://www.huaweicloud.com/intl/en-us/product/bcs/nes.html
@apeslee on Telegram or wuhuama#0 on Discord

**Comment by supportnode3** [comment]
Hello there!

We sincerely apologize for the delay in submitting our application. [Node3](https://www.node3.tech/) is fully dedicated to decentralization, planning to operating 50,000 validators with a focus on both EL and CL minorities. Our infrastructure, located in Australia, is exclusively on-premises and dedicated to Holesky over lifetime.

If it remains feasible, we kindly request you to reach out to me through Telegram at @peterlin0509 or via email at [peter.lin@node3.tech](mailto:peter.lin@node3.tech). Thank you for your understanding.

Much appreciated!

**Comment by crypto-services** [comment]
Apologies for the late response.

Republic Crypto would be happy to run 10k validators for the lifetime of Holesky. We can situate the infrastructure where ever is best suited to improve coverage/decentralisation and our infrastructure team is on-call 24/7 to maintain uptime.

You can contact us directly via email [here](mailto:runtime-support@republiccrypto.com).

**Comment by Alpha-nodes** [comment]
I'm reaching out to propose deploying 20,000 validators on the Holeskie platform under our Alphanodes project. We're fully committed to this initiative, considering both hardware specifications and security requirements. We have the flexibility to host the validators in any geographical location that meets our performance and regulatory criteria.

If this aligns with your roadmap, please get in touch with me either through Telegram @Alphanodes23 or via email at limeneris@gmail.com to discuss next steps.
