### ISSUE TITLE
Precompiles are not pre-funded

### ISSUE THREAD

**Issue by jochem-brouwer** [eth-clients/holesky#14]
I just saw the genesis file and noticed that the precompiles are not pre-funded. We should do so, otherwise we get behavior of accounts being deleted even if the call frame gets reverted (RIPEMD160, tx 0xcf416c536ec1a19ed1fb89e4ec7ffb3cf73aa413b3aa9b77d60e4fd81a4296ba)

**Comment by q9f** [comment]
Yes, we should do this. Good point.

**Comment by jochem-brouwer** [comment]
Great, thanks!
