### ISSUE TITLE
Genesis validator tracker

### ISSUE THREAD

**Issue by q9f** [eth-clients/holesky#2]
The validator set will be public, please indicate if you desire to run a genesis validator. We might reserve the right to limit genesis participation to existing client teams, staking communities, and pools for now.

Format: Institution / `Desired number of validators` / `contact`

- Goerli Initiative / `20_000` / `@afr:tchncs.de`
- CryptoManufaktur / `20_000` / `yorickdowne@cryptodon.lol`
- EF DevOps / `100_000` / `devops@ethereum.org` _(Also willing to do 200k depending on total target size)_
- lightclient / `10_000` / `@lightclient` on tg
- EthStaker / `10_000` / `@remy_roy` on twitter
- ralexstokes / `10_000` / `@ralexstokes` on tg
- dapplion / `10_000` / `@dapplion` on twitter

**Comment by yorickdowne** [comment]
CryptoManufaktur / 20_000 / @yorickdowne@cryptodon.lol

**Comment by parithosh** [comment]
EF DevOps / `20_000` / @[devops@ethereum.org](mailto:devops@ethereum.org)

**Comment by lightclient** [comment]
lightclient / `20_000` / @lightclient on tg

**Comment by remyroy** [comment]
EthStaker / `10_000` / @remy_roy on twitter

**Comment by ralexstokes** [comment]
ralexstokes / `10_000` / @ralexstokes on tg

**Comment by dapplion** [comment]
dapplion / `10_000` / @dapplion on twitter

**Comment by Emilijus436** [comment]
Emilijus436 / `10_000` / [emilijusbanikonis20@gmail.com](url)

**Comment by Emilijus436** [comment]
Emilijus436 / `10_000` / [emilijusbanikonis20@gmail.com](mailto:emilijusbanikonis20@gmail.com)

**Comment by NachoColl** [comment]
BWS / 10_000 / nacho.coll@bws.ninja

**Comment by nalepae** [comment]
We run thousands of validators on mainnet (and goerli).
We also have 100 validators on sepolia.

[Kiln.fi](https://www.kiln.fi/) / `10_000` / @ManuNLP on TG.

**Comment by 0xalex88** [comment]
We run 4k+ validators on mainnet and a few on goerli.

frax.finance / `10_000` / alex@frax.com

**Comment by sambacha** [comment]
manifold finance & securerpc.com / `36_000` / [sam@manifoldfinance.com](mailto:sam@manifoldfinance.com) @sambacha on Telegram


Set of validators would be split between providing baseline multi client validator and beacon setup and the other half for testing updates for nodes, relay etc.

**Comment by antondlr** [comment]
sigma prime / `50_000` / devops at sigmaprime dot io (or any other of the known comms channels)

**Comment by protolambda** [comment]
protolambda / `10_000` / `@protolambda` on TG.

Looking to run one or two dedicated nodes with validators

**Comment by zhongfu** [comment]
zhongfu / `10_000` / `@zhongfu` on TG

**Comment by q9f** [comment]
Superseded by #11 #12 #13

**Comment by infosecual** [comment]
dtheo (EF Security Research) / `10_000`/ `@infosecual` on TG
