### ISSUE TITLE
Genesis validator pubkey tracker

### ISSUE THREAD

**Issue by q9f** [eth-clients/holesky#24]
Client Teams
- [x] ConsenSys: `100_000` #28 
- [x] EF DevOps: `50_000` #27
- [x] Lodestar: `100_000` #21 
- [x] Nethermind: `100_000` #38 
- [x] Nimbus: `100_000` #41 
- [x] Prysm: `100_000` #31 
- [x] Sigma Prime: `100_000` #36 
- [x] Grandine: `50_000` #39
- [x] Erigon: `5_000` #33 
- [x] Besu: `100_000` #32 

Node Operators
- [x] Attenstant: `50_000` #20 
- [x] Kiln: `100_000` #35 
- [ ] Manifold: `100_000`
- [x] P2P Validator: `100_000` #42 
- [ ] Pier Two: `100_000`
- [x] RockawayX: `100_000` #45 
- [x] Rocket Pool: `50_000` #46 
- [x] RockX: `50_000` #44
- [x] Stakely: `50_000` #43 
- [x] CryptoManufaktur: `20_000` #19 
- [x] Chainstack: `10_000` #29 
- [ ] Simply staking: `10_000` 

Others
- [x] EthStaker: `40_000` #30 
- [x] Goerli (Afri): `20_000` #25 
- [x] arnetheduck: `10_000` #37 
- [x] Sam Padilla Google (GCP): `10_000` #47
- [x] Chainbase: `20_000` #26
- [ ] Blockblaz (Gajinder): `10_000`
- [ ] dapplion: `10_000`
- [x] protolambda: `10_000` #51 
- [x] ralexstokes: `5_000` #50 
- [x] EF Security: `10_000` #34

**Comment by barnabasbusa** [comment]
Please submit your PR by Friday 18th of Aug 2023 23:59 UTC. Please read the docs about how to create the PR [here](https://notes.ethereum.org/@ethpandaops/Holesky-onboarding). Please make a PR if you see your name/organization on the list.

**Comment by infosecual** [comment]
EF Security Research did not get included in this list even though we asked for an allocation before the deadline https://github.com/eth-clients/holesky/issues/13#issuecomment-1613170173. Can we please get added back into the list?

**Comment by theSamPadilla** [comment]
You can remove me from the list (` Sam Padilla (GCP): 10_000`) since you already added Google Cloud.

ref #47

**Comment by barnabasbusa** [comment]
@theSamPadilla thanks, updated.
