### ISSUE TITLE
Please don't abbreviate to "holli"

### ISSUE THREAD

**Issue by chrishobcroft** [eth-clients/holesky#4]
__Auto-translated czech-language version is below.
Níže je uveden automatický překlad do češtiny.__

The "Holešovice" network is named after Nádraží Holešovice in Prague in Czech Republic.

I can understand why the Goerli testnet, named after "Goerlitzer Bahnhof" in Berlin, is abbreviated to "goerli"... everyone in Berlin calls it "goerli", same same like everyone called Kottbusser Tor "kotti".

But nobody (I repeat, nobody) in Prague calls Holešovice "holli". Abbreviating to this would be using a Berlin-centric pattern for abbreviation, and is not appropriate in the context of Prague. This is not to mention the use of 2 "L" letters, which don't appear in the elongated version.

Proposed alternatives:

- Don't abbreviate: use the full name of the station: `-holesovice`, it really isn't that complicated to spell,

- Only truncate, don't alter: "hole" or "holes" are both better than "holli"

If none of these are acceptable, then I propose to choose a different name for the testnet, because using "holli" as an abbreviation for Holešovice is incongruous.

Translated to Čeština via deepl:

Síť "Holešovice" je pojmenována podle Nádraží Holešovice v Praze v České republice.

Chápu, proč se testnet Goerli, pojmenovaný podle "Goerlitzer Bahnhof" v Berlíně, zkracuje na "goerli"... všichni v Berlíně mu říkají "goerli", stejně jako všichni říkají Kottbusser Tor "kotti".

Ale nikdo (opakuji, nikdo) v Praze neříká Holešovicím "holli". Zkracování na tuto adresu by bylo používáním berlínského vzoru pro zkracování a v kontextu Prahy není vhodné. A to nemluvím o použití 2 písmen "L", která se v prodloužené verzi nevyskytují.

Navrhované alternativy:

- Nezkracovat: používat plný název stanice: `Holešovice`, opravdu není tak složité ho napsat,

- pouze zkracovat, neměnit: "díra" nebo "díry" jsou obě lepší než "holli".

Pokud nic z toho není přijatelné, pak navrhuji zvolit pro testnet jiný název, protože používat "holli" jako zkratku pro Holešovice je nesourodé.

Přeloženo do češtiny přes deepl:

**Comment by dmon1e** [comment]
I wholeheartedly agree - using holli to represent holesovice is unfathomable. 

Make Holesovice great again and keep the original spelling!

**Comment by burningtree** [comment]
I totally agree. I'm native Czech living in Prague almost all my life and I've never heard "Holli".

Holešovice is not just a train stop, but an entire Prague district (before city) with a rich history dating back to the 12th century. So calling it Holli is nonsense.

Greetings from Prague! 🇨🇿  Díky moc, kamarádi

**Comment by jaczkal** [comment]
Agree, I'm also native Czech living in Prague and Holli is pure nonsense.

If we still would like to abbreviate, I will choose `--holesky` with pronunciation of Holešky (which is imho acceptable and used abbreviation of Holešovice) because it will be funny to see people pronunciating as a testnet that is a hole in the sky.

**Comment by chrishobcroft** [comment]
It can also sound like "whole sky", which could be either good, great or terrible.

**Comment by q9f** [comment]
Thank you for raising this. Fortunately, the name is not set in stone yet.

Unless anyone vetos, I would love to go with Holešky. 🖤

**Comment by JosefJ** [comment]
I also support this act of local patriotism!! 💪

Also for more context that part of Prague 7 is sometimes referred to as "mokřad", meaning a wetland (https://en.m.wikipedia.org/wiki/Wetland)

**Comment by chrishobcroft** [comment]
Question: why does it need to be abbreviated, why not just let it be called Holesovice, and write `--holesovice` in full?

Olympic, Morden, Rinkeby, Ropsten, Kovan were always defined via full names. Testnet names only started being abbreviated with Goerli (and arguably the short-lived Kotti)... but that precedent doesn't need to be followed...

For example, `./geth --holesovice` can work...

**Comment by sambacha** [comment]
Why are test nets and hardforks named after cities? Why cant we name it after something else like people perhaps?

**Comment by q9f** [comment]
> Question: why does it need to be abbreviated, why not just let it be called Holesovice, and write `--holesovice` in full?
> 
> Olympic, Morden, Rinkeby, Ropsten, Kovan were always defined via full names. Testnet names only started being abbreviated with Goerli (and arguably the short-lived Kotti)... but that precedent doesn't need to be followed...
> 
> For example, `./geth --holesovice` can work...

To make it more accessible for an international audience.

**Comment by chrishobcroft** [comment]
> To make it more accessible for an international audience.

I don't think it's worth adding the complexity to truncate "holesovice" to "holesky" and this arguably makes it less accessible for an international audience, having to learn both words.

Learning to spell "holesovice" feels the same rough order of magnitude of complexity as to learn "holesky", but learning just one term is half as complex as learning two.

**Comment by chrishobcroft** [comment]
(I mean, it's not as though there are any accents to type)

**Comment by jaczkal** [comment]
On the other hand, when people will learn "holesky", it will give them additional "flex factor" during their visit of Prague

**Comment by qSlnz** [comment]
Please keep it simple, "holesovice" can be very uncommon to some languages and lead to mistakes. Paying homage is one thing, but let's not forget that the goal is to find a simple name that can be easily remembered and reused by developers around the world.

**Comment by RiccardoBiosas** [comment]
imho i prefer the `-holesovice` flag, it is as straightforward to spell as it is true to the original name of the Prague district
