### ISSUE TITLE
Holesky DNS Network for Peer Discovery

### ISSUE THREAD

**Issue by holgerd77** [eth-clients/holesky#58]
Hi there,
Holger from EthereumJS here, we have just integrated the Holesky testnet into our client codebase https://github.com/ethereumjs/ethereumjs-monorepo/pull/2982 , excited for the launch ! 🎉

When looking over the configuration I wondered, will there be a DNS server/network for peer discovery as being setup for Sepolia or Goerli (with a URL like `enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.sepolia.ethdisco.net`)? And if so will it be active from the start on?

I think normally people from Go Ethereum run these servers, maybe tagging her @holiman therefore? 🤔

If there is/will be a DNS server available it would also be nice if the address can be added to the initial README description.

Ok, so far, have a great testnet start! 🙂 🙏

**Comment by parithosh** [comment]
Hey! We're gonna look into this and try to get it done asap, unsure if it'll make it in time for all client releases though. It'll land up on the same domain, `all.holesky.ethdisco.net`.

**Comment by parithosh** [comment]
Martin deployed the PR to add support for Holesky. You can check the data here: https://github.com/ethereum/discv4-dns-lists

` dig all.holesky.ethdisco.net ANY` responds with a `enrtree-root` now.

**Comment by holgerd77** [comment]
Very cool and thanks a lot (also to Martin) 🙏, we will try out very soon and give a quick feedback here! 🙂 

Might also be a good idea to re-post respectively point to here in R&D Discord #testnets or so channel for visibility.

**Comment by holgerd77** [comment]
Ah, and this should likely also be added to the metadata section [here](https://github.com/eth-clients/holesky#metadata)?

**Comment by holgerd77** [comment]
Ah sorry, never came back to this. Just a late confirm that this works fine, here is an extract from our devp2p logs on a Holesky run:

![grafik](https://github.com/eth-clients/holesky/assets/931137/b59767a6-d645-4d71-aa55-097e622b0a68)

**Comment by parithosh** [comment]
Thanks for the update! I'll close the issue and merge the respective PR then :)
