### ISSUE TITLE
Add Holešky pronunciation

### ISSUE THREAD

**Issue by abcoathup** [eth-clients/holesky#64]
Can we get a guide on how to pronounce Holešky (including audio) added to the top of the README?
Prior to genesis is the time to get the message out of how to say it correctly (for devs, educators, media).

["holskiii", not "hole-sky"](https://twitter.com/TimBeiko/status/1692286962877776098)
["Holeshki", h is vocal like home, Y like a single e](https://twitter.com/DCbuild3r/status/1692655456722845941)

**Comment by chrishobcroft** [comment]
Perhaps @jaczkal can help as it was they who proposed the name in the first instance? :)

**Comment by chrishobcroft** [comment]
I will have a go:

The "Hol" is like the "hol" in "holiday".

The "e" is pronounced like the "e" in "extra".

The š (with háček) is pronounced as a "sh".

The "ky" is pronounced like "key".

I don't know how better to describe it.

**Comment by abcoathup** [comment]
A playable audio would really help (Peepeth had this: https://peepeth.com/a/name)
Perhaps add to: https://www.howtopronounce.com/search/czech/Hole%C5%A1ky

**Comment by taxmeifyoucan** [comment]
Wiki offers phonetic pronunciation of Holešovice, might be helpful https://en.wikipedia.org/wiki/Hole%C5%A1ovice

**Comment by dcbuild3r** [comment]
I'm happy to record a playable audio, what would be a good platform to do that on?

**Comment by jaczkal** [comment]
Sure, Chris described it nicely in a human manner and we can also write down IPA compliant pronunciation. Inspiration: https://en.wikipedia.org/wiki/Holešovice

Holešovice (Czech pronunciation: [[ˈɦolɛʃovɪtsɛ]](https://en.wikipedia.org/wiki/Help:IPA/Czech))

and thus, with some help of GPT, we have:

Holesky [ˈɦolɛʃki]

This can be passed to any IPA text to speech reader, eg. found this https://itinerarium.github.io/phoneme-synthesis/

So at the end, there could be the human version but also the rigorous (both written and spoken)

**Comment by dcbuild3r** [comment]
sounds bad using the IPA text to speech reader ngl (as a native czech person)

**Comment by jaczkal** [comment]
agree on the example what I sent, maybe there are better interpreters

**Comment by dcbuild3r** [comment]
I just recorded myself using [vocaroo](https://voca.ro/12M6Re2fS8KV). I said "Holešky, Holešovice, Holešky".

**Comment by dcbuild3r** [comment]
I'm happy to create a PR and append the audio file to the repo

**Comment by taxmeifyoucan** [comment]
@jaczkal +1 to using IPA. `Holešky [ˈɦolɛʃki]` should be added to the preface. 

Even tho I like the idea of being clear about the local Czech pronunciation, I wouldn't push for strict rules or audio for pronouncing it exactly this way. As with other testnets, we will end up with bunch of different variations ('Hole in the Sky' already popular now) and I find that beautiful :)

**Comment by dcbuild3r** [comment]
IPA is definitely good, but I think having a correct reference pronunciation is good. If you feed it to an IPA reader it sounds terrible. I'm happy with people pronouncing it however they want as long as it is unambiguous. It's hilarious to see things like hole in the sky, whole sky, etc

**Comment by abcoathup** [comment]
> Even tho I like the idea of being clear about the local Czech pronunciation, I wouldn't push for strict rules or audio for pronouncing it exactly this way. As with other testnets, we will end up with bunch of different variations ('Hole in the Sky' already popular now) and I find that beautiful :)

I'm keen for guidance on local Czech pronunciation, especially an audio, so that I don't do a horribly mangled version in my Australian accent.

**Comment by q9f** [comment]
I refuse to engage in this discussion until we figure out the Goerli pronunciation first.

**Comment by chrishobcroft** [comment]
That's easy. It's like "girlie", right?

**Comment by arnetheduck** [comment]
What about ropsten? Plenty of amusement for us swedes that's gone now

**Comment by q9f** [comment]
_Rooohpsten_

**Comment by radeksvarz** [comment]
Holesky? Just using "holy sky" ... ;)

**Comment by q9f** [comment]
Closing as it is actually desired to have no clear definition of the pronunciation.
