### ISSUE TITLE
Get Holesky Testnet Ether

### ISSUE THREAD

**Issue by vieyang** [eth-clients/holesky#82]
Just as [Goerli #106](https://github.com/eth-clients/goerli/issues/106) did:

Missed genesis validator? Post your Holesky address and the desired amount.

Rules: 100 ETH/3 Validators max

Update: Closed until issues are resolved.

**Comment by vieyang** [comment]
I missed the  Holesky genesis validator and I want to apply for 10 validators.

321 ETH for 10 validators

Address: 0x608f1a0a6859723be79B24A2FfCB377D92e25222

**Comment by 0xMaxMa** [comment]
Hi, I'm looking to apply 3 validators.

Desired amount is 100 ETH.
Address: 0xddDDd3bf0B0d7df20B0376b51b8c9e8F5968Ae4B

Thanks.

**Comment by ArturDolzan** [comment]
Hi there,
Can I get 3200 tokens to apply 100 validators in k8s env? 

Address: `0xbb1de7bB6049a20ec360f26d468337476Ce2D38F`

Thanks.

**Comment by larryannon** [comment]
Hello, I need 32000  ETH to run 1000 validators for testing

Address: `0x06Fe29F0c724f84Cd18FB2e5e62eD0aC336Ab04D`

Thanks.

**Comment by yagolgmesol** [comment]
100 ETH Holesky for validators quite a lot thanks!
0xE1d94C640265c54dBf17Fe75e4e0970A56e722Dc

**Comment by 0xMaxMa** [comment]
> > Hi, I'm looking to apply 3 validators.
> 
> > 
> 
> > Desired amount is 100 ETH. Address: 0xddDDd3bf0B0d7df20B0376b51b8c9e8F5968Ae4B
> 
> > 
> 
> > Thanks.
> 
> 
> 
> 
> 
> You can get 100 tokens in the official faucet quite quickly (you can get 100 per day at the moment) https://holesky-faucet.pk910.de/

Oh, many thanks

**Comment by 0xNODE3** [comment]
Hi there,

We extend our sincerest apologies for our previous oversight in joining the HoleSky Gnosis. Node3 is wholeheartedly committed to decentralization, with plans to oversee 50,000 validators/keys for Holesky, focusing on both EL and CL minorities. Our infrastructure located in Australia and Brazil, is entirely on-premises and dedicated to Holesky for the long term.

We are inquiring whether it would be possible for us to join Gnosis or alternatively, if we could provide the requisite Holesky ETH (approximately 1,500,000 ETH) to the address 0x8fB2fC33Db076e88DEE90a40a4E42A20c67bc19d. While we are aware of the faucet available at https://holesky-faucet.pk910.de/, regrettably, the provision of 100 daily does not meet our operational needs.

We kindly ask that you contact me through Telegram at @Alison_Node3 or via email at [alison.carter@node3.tech](mailto:alison.carter@node3.tech). We greatly appreciate your understanding.

Much appreciated
Node3

**Comment by ZidarLoyn** [comment]
We need 12000 ETH to run validators for testing

**Comment by ZidarLoyn** [comment]
We need 12000 ETH to run validators for testing,Tnx🙏🏼
0xA424Bdb67d16Ff6e40172234340e586A3396f2cB

**Comment by mantasciuksys** [comment]
Humbly requesting 20,000 ETH of Holesky for Tatum.io (JS SDK and Nodes for Ethereum) 

0x712e3a792c974b3e3dbe41229ad4290791c75a82

**Comment by micovi** [comment]
Looking to spin up some validators on Holesky to test DVT
Requesting 8000 ETH

0x31a36dE53b87a2773Ab5c00699B91d6eE4f7Ee93

**Comment by Kangradin** [comment]
Hi, We need about 16000 holesky eth to run 500 validators, thanks
0xEE94a2fA9901D662EcE32993bEBe237e8d1d3A99

**Comment by vieyang** [comment]
https://holesky.ethpandaops.io/
