### ISSUE TITLE
How to switch from Goerli to Holesky

### ISSUE THREAD

**Issue by makkanlover** [eth-clients/holesky#83]
Hi there,

Sorry for the suddenness. I am currently running an Eth node operation in Goerli.
I am thinking of switching to Holesky because Goerli will be unavailable after the new year, but I am still new to node operation and my knowledge is still insufficient.
After reading the README, I understand a few things such as changing the Flag to holesky, Network ID and Chain ID need to be changed.

With this update to Holesky, how hard would it be to switch from the existing Goerli?
I would like to switch without destroying the environment I created, but should I set up Holesky from scratch?
I'm still a beginner and don't really know what I'm doing, so I would appreciate it if someone could help me out.

**Comment by rocknet** [comment]
Hi there. Basically what you’ll need to do is 

- Shut down your clients
- Delete the chain db directories. Depending on client and config, there may be a goerli sub folder, or it may be in a single chain-db folder
- Update EL and CL clients to a Holesky supporting version
- Just change the network flag from your current config. The network flag has all the required config like Chain ID built into it. This is why the client teams did Holesky releases. 
- Restart the clients 

If you’re running validators, before doing the above you should exit them cleanly, even though the chain is scheduled for deprecation. 

For more help, something like this may be better handled in discord where you can get interactive help. I’d recommend EthStaker, Rocket Pool, and / or you selected clients respective discord servers. Ethstaker.cc and rocketpool.net have the discord links, they’re both super helpful. RP has a #support channel, as well as a thread in #trading dedicated to running holesky validators.

**Comment by makkanlover** [comment]
Thank you for your quick reply.
I see that it is sufficient to just modify the flag for config settings.
I am not a validator, so it will only be a minor modification.
I am relieved to know that even a novice like me can switch to Holesky.
