### ISSUE TITLE
ERC1820 contract cannot be deployed

### ISSUE THREAD

**Issue by OleksanderSalamatov** [eth-clients/holesky#89]
ERC1820 contract cannot be deployed because it has no chainID in transaction, which blocks all ERC777 tokens tesing on network

Using ankr endpoint for testing, got error `Error: legacy pre-eip-155 transactions not supported`

**Comment by DimaStebaev** [comment]
Is it possible to somehow temporary disable [EIP-155](https://eips.ethereum.org/EIPS/eip-155) to deploy [ERC-1820 smart contract](https://eips.ethereum.org/EIPS/eip-1820#deployment-transaction)?

**Comment by zhongfu** [comment]
deployed https://holesky.etherscan.io/tx/0xfefb2da535e927b85fe68eb81cb2e4a5827c905f78381a01ef2322aa9b0aee8e

**Comment by DimaStebaev** [comment]
Thank you!
I think the issue is resolved.
